### ISSUE TITLE
Favicon needed for app.geo.ca

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/app.geo.ca#11]
Here are the favicon png for use throughout the site:

![logo_geo_164x70](https://user-images.githubusercontent.com/18405829/202013662-fb7b473b-2cb1-44c8-9b4b-c6f84f117cf3.png)
![icon-GEO-300x300](https://user-images.githubusercontent.com/18405829/202013665-9d559e8d-9af6-4276-b2a8-aa545c298546.png)
![icon-GEO-150x150](https://user-images.githubusercontent.com/18405829/202013667-90c21db5-3dbe-4841-822d-5151f20a3857.png)

**Comment by jvanulde** [comment]
Can we close @bo-lu?

**Comment by bo-lu** [comment]
Yes, let's close it
