### ISSUE TITLE
Display STAC thumbnails in the metadata details page and main map when clicking 'View footprint'

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/app.geo.ca#116]

**Comment by bo-lu** [comment]
On the main map, it should also zoom to the bounding box upon clicking 'View footprint'.

Important to verify how accurately georeferenced is the thumbnail. It seems to be good on STAC Browser:
https://radiantearth.github.io/stac-browser/#/external/datacube.services.geo.ca/api/collections/napl-victoria?.language=en&.itemFilterOpen=1

Toggle 'Reset' and 'Next' to see that it is very accurate.

Sample view on the metadata details page:
<img width="510" alt="demo" src="https://github.com/Canadian-Geospatial-Platform/app.geo.ca/assets/18405829/3441574c-4e7f-4ca9-910d-6cf9f698d816">

**Comment by xinli-cai** [comment]
Related to geo.ca issue [#134 ](https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/134) - View STAC records on the app.geo.ca viewer. Noted, #134 is for app.geo.ca version 2, #116 is for current app.geo.ca.

**Comment by bo-lu** [comment]
Fully deployed in dev. Staging is pending
