### ISSUE TITLE
Readme: `expore` spelling ambiguity (and others in a collected rollup)

### ISSUE THREAD

**Issue by maphew** [Canadian-Geospatial-Platform/app.geo.ca#130]
_[Later]._ I'm seeing more typos as I read through the docs. Rather than make a new issue for each typo and broken link, I'll just update this top post wiki style.

- [x] https://github.com/Canadian-Geospatial-Platform/app.geo.ca/blob/c834507c72fde8f1f843dc876ad58cbb2421aa9b/README.md?plain=1#L3. It says `expore`, probably meant `expose` , but might have intended `explore`.  
Same spelling in https://canadian-geospatial-platform.github.io/app.geo.ca/
- [x] ToC heading mispells "application"
- [x] ToC at https://canadian-geospatial-platform.github.io/app.geo.ca/docs/build-instructions/ has broken link to 'Build Document'
- [ ]

**Comment by bo-lu** [comment]
Thanks for the bug report, these were fixed in this commit:
https://github.com/Canadian-Geospatial-Platform/app.geo.ca/commit/cc49be1b2a82eb4f4c66d3e446ecda0ed17b8bef

I check the documentation page and it has been automatically rebuilt
