### ISSUE TITLE
User Story: 'Metadata Source' filter on app.geo.ca

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/app.geo.ca#132]
As a user, I want to be able to filter search results by Metadata Standards.

The rationale for this user story is that some of the CCMEO Data Cube records are also described by HNAP metadata entries, causing duplication of records. To address this issue, we propose adding a filter that allows users to search only for HNAP or STAC records while defaulting to both. An example mockup is shown below:

When initiating a search, the default behavior is to search all available metadata. Alternatively, users can choose to only search HNAP records. They can also turn standards on or off as desired.
![Mockups_metadata_standards1](https://user-images.githubusercontent.com/103012417/219704780-cf16c3bd-ad19-4d10-bfeb-1cdaac30399a.png)
![Mockups_metadata_standards2](https://user-images.githubusercontent.com/103012417/219704801-29b499c1-7979-477b-b6bf-78d95a13dd7d.png)

**Comment by xinli-cai** [comment]
@bo-lu @johnweng001 FYI

**Comment by bo-lu** [comment]
I will work on the backend after wrapping up the popularity and date filters.

@johnweng001, can you work on the front-end components? Thanks!

**Comment by johnweng001** [comment]
@bo-lu yes, I am on it.

**Comment by bo-lu** [comment]
Parent user story is: Canadian-Geospatial-Platform/geo.ca#70

**Comment by bo-lu** [comment]
Instead of a 'Metadata Standard' filter, which is not useful and potentially confusing for users, maybe we can create a 'Metadata Source' filter. 

Current sources are: the Canadian Geospatial Platform, CCMEO Datacube and the Earth Observation Data Management System (EODMS)

**Comment by bo-lu** [comment]
![image](https://github.com/Canadian-Geospatial-Platform/app.geo.ca/assets/18405829/69ef47f7-8edb-4022-a39a-81ed98bb93b1)

![image](https://github.com/Canadian-Geospatial-Platform/app.geo.ca/assets/18405829/47cb73e2-835b-4248-aad5-581854944b39)


Thank you John, it is working well on dev
