### ISSUE TITLE
Advanced Search Filters - EODMS Source doesn't show any results

### ISSUE THREAD

**Issue by Lanthierya** [Canadian-Geospatial-Platform/app.geo.ca#155]
Using the Keyword only/Advanced Search option:

- [x] Selecting SENTINEL-1 in the list yields no results.

- [x] Also need to use clean URL without language keywords.

**Comment by bo-lu** [comment]
Sentinel-1 datasets now restored. I think it was an issue with the filtering.

Removed some code which was causing issues with filtering. 

- [x] Created new session variable which will reset the local storage variable after 5 minutes have elapsed.
