### ISSUE TITLE
The new line character \n\n is showing in the search result's description

### ISSUE THREAD

**Issue by johnweng001** [Canadian-Geospatial-Platform/app.geo.ca#24]
Reproduce steps:
go to https://app.geo.ca/
1. click search icon
2.  choose keywordonly
2.  type "gold" in the search
3. in the first item of search result, observe the \n\n is showing in the description
These structure, isopach and zero edge files are part of a series of stratigraphic framework maps for the Saskatchewan Phanerozoic Fluids and Petroleum Systems (SPFPS) project.\n\nThe series of stratigraphic framework maps for the Sa

**Comment by bo-lu** [comment]
Hi John,

Can you link to the branch for this work?

Thank you,

Bo

**Comment by johnweng001** [comment]
hi Bo,
The fix is in dev-issue24. 
PR has been created.
Thanks
