### ISSUE TITLE
Copyright year is incorrect

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/app.geo.ca#26]
In the footer we have:

© His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources Canada, 2022

Should be: 

© His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources Canada, 2023

Ensure that this is changed on French UI as well.

**Comment by jvanulde** [comment]
@elatsis FYI I added this as a high priority in the pipeline to ensure that is gets deployed in our next release.

**Comment by johnweng001** [comment]
The copyright year is fixed in branch dev-issue26copyright. 
PR has been created.

**Comment by bo-lu** [comment]
app.geo.ca now shows: © His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources Canada, 2023
