### ISSUE TITLE
User Story: Add caching to geo and id lambda functions using ephemeral storage

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/app.geo.ca#29]
As a developer I would like to define global variables in lambdas to allow storage of cached results. 

- [ ] Requires a provisioned lambda so cache is not destroyed every ~45 minutes
- [ ] Requires a cache replacement strategy to invalidate the cache. For example, either a timestamp to invalidate the cache (e.g., every 14 days) or a check to see if a reharvest has occurred by checking the 'change' API.
- [ ] The storage structure of the cache should be a hash table for constant time for insertion and search. Average cases are O(1). Search key will be the keyword, followed by an if statement to determine if the cache is still valid for that keyword, and will finally either return the cached result or the underlying API.

Reference (Option 1):
https://blog.devgenius.io/aws-lambda-caching-why-and-how-bd3c2d500c

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/app.geo.ca/29?planning-poker) with Zenhub @bo-lu
