### ISSUE TITLE
Create User Portal Page

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/app.geo.ca#6]
Create User portal page for logged in user to show case:

Saved Searches
Saved Records

Community Membership (Once Communities in place).

Must be able to delete saved records as well.

**Comment by ehfounder** [comment]
@raviinder 

- Remove the top "general" announcement section on the user dashboard.
- Move the saved search and saved record to the top above the community announcements.
- push your changes to the "features" branch for review by @jvanulde and I
