### ISSUE TITLE
Default list of records not adhering to default Sort by option (i.e. Title)

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/app.geo.ca#95]
<img width="515" alt="Screen Shot 2023-06-15 at 7 48 59 AM 1" src="https://github.com/Canadian-Geospatial-Platform/app.geo.ca/assets/2255248/f34a57aa-2c31-4bb5-a8f2-d15b3a9f0633">

**Comment by johnweng001** [comment]
@bo-lu 
sort=title is sent from frontend.
can you check api side?
